### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by freis** [cdiaz/nest-passport#1]
I was trying around your build and when I did:
const user = { sub: 10, email: 'jodhndoe@nestjs.com' };

this user does not exist I get the following. Any recommendations?

> (node:9516) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): User not found
(node:9516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cdiaz** [comment]
Hi, please describe in detail, the steps necessary to reproduce the problem.

If you have changed the id key by sub you must make sure that you are find the same key:

`const user = this.users.find((user)=> user.sub === +sub);
`

I am using users[] array only to provide a quick example, the best way is to use a database, in this case I recommend [Fusedb](https://github.com/fuse-box/fusedb).

**Comment by freis** [comment]
I'm using TypeORM. But I think i'm the one to blame. What I was trying to check what would happen if the sub wasn't present on the database. But I think that if its not it will never create the token because it will fail before on the logging in part.

**Comment by cdiaz** [comment]
I understand; You just have to do the validation and throw the exception
```
if (user.length === 0) {
  return reject (new HttpException ('User not found', 401))
}
```
Good luck
